### ISSUE TITLE
Allow defining an alternate keymap in a config file

### ISSUE THREAD

**Issue by Alphare** [markbt/streampager#17]
When @markbt and I saw each other and he showed me `streampager`, we talked about how the current keyboard shortcuts don't play nice with certain keyboard layouts like AZERTY. 

I'm opening this issue not because I expect anyone else to put in the work but to gauge interest and get opinions about implementation in case I ever get the free time needed to add this feature.

Thanks!

**Comment by markbt** [comment]
I'm planning to make it easier to define keymaps (with the intention of making it possible to run sp with customized keymaps), so I'll let you know when that's done and you can add something for azerty.  We can probably define sensible defaults per locale, and load the one for the user's locale.
