### ISSUE TITLE
Search query should be remembered for next run

### ISSUE THREAD

**Issue by martinvonz** [markbt/streampager#38]
`less` remembers the last thing you searched for so you can just press "n" to search for it again next time. It would be nice to have the same feature in streampager.

**Comment by markbt** [comment]
I don't think I'd ever used that feature of `less` before.  We do have the search history (`/`, `Up`), so it shouldn't be too hard to implement this.

**Comment by martinvonz** [comment]
Ah, I didn't realize that you had search history (nice!). Just `n` is still a nice shortcut, but `/`,`Up` is good for now, thanks.

**Comment by markbt** [comment]
When I get round to this, I should also add shortcuts for "jump to next/prev match relative to the current screen position" (cc @quark-zju).
