### ISSUE TITLE
Add mode that doesn't consume key presses before `sp -X` switches to fullscreen

### ISSUE THREAD

**Issue by martinvonz** [markbt/streampager#39]
I sometimes do `hg st` quickly followed by `hg <something>`. With `less`, the second `hg` can be typed while I wait for output from `hg st`, but streampager eats my input. I don't know how much of an issue this is; perhaps I'll soon get used to waiting for the prompt to appear before I type.

I noticed that the README says that, with `-X`, "output will be displayed directly to the terminal until either a full screen of input is received, or Space is pressed" (I couldn't get Space to switch to fullscreen mode, btw). I don't know if that would make it hard to support this feature or if the system calls will let you peek and see if the user has pressed Space.

**Comment by markbt** [comment]
You can't peek the input without consuming it, unfortunately, but we can make this behaviour optional.  I'll add it to the feature request list.
