### ISSUE TITLE
Streampager eats my colors when using `delta` as a pager

### ISSUE THREAD

**Issue by Alphare** [markbt/streampager#42]
I gave https://github.com/dandavison/delta/ a try (for both Git and Mercurial), and I was scratching my head as to why only some of the colors worked.

The culprit seems to be `streampager`, because when falling back to `less`, the colors are fine again.

**Comment by markbt** [comment]
It looks like `delta` emits `EraseToEndOfLine` sequences (`CSI 0 K`), which currently `streampager` ignores.  It shouldn't be too hard to add support, though.
