### ISSUE TITLE
Backport changes from Sapling?

### ISSUE THREAD

**Issue by yuja** [markbt/streampager#61]
Hi, do you have any plan to backport changes from Sapling fork? (or release it with different name?)
https://github.com/facebook/sapling/tree/main/eden/scm/lib/third-party/streampager

In particular, I'm interested in

* split binary crate (and/or update clap to 4.x)
* update other dependencies
* add feature flag that drops "notify" dependency

I can send PRs, but I suspect that it would be undesired to maintain separate branches.

**Comment by martinvonz** [comment]
Alternatively, maybe you could publish new versions from the fork in the Sapling repo. That's less attractive to me, but I'm guessing there's a reason you created the fork instead of having Sapling just depend on this versions published from here.

**Comment by quark-zju** [comment]
> Alternatively, maybe you could publish new versions from the fork in the Sapling repo. That's less attractive to me, but I'm guessing there's a reason you created the fork instead of having Sapling just depend on this versions published from here.

It was for fast iteration. Changing streampager, reviewing, publishing to crates.io, updating internal version takes time. Code review by other team members can also offload @markbt. Although we haven't utilized the "fast iteration" benefit that much.

Publishing from sapling could be a reasonable choice. We now have a [team account](https://crates.io/teams/github:facebook:cratesio-publish) so it's easy for any team member to publish - no longer blocks on one person.

I'll let @markbt decide what to do next.

**Comment by martinvonz** [comment]
@markbt, what's your preference?

**Comment by quark-zju** [comment]
Sorry for the delay. It's now published at https://crates.io/crates/sapling-streampager

**Comment by yuja** [comment]
Many thanks!
