### ISSUE TITLE
streampager doesn't notice input file changing

### ISSUE THREAD

**Issue by jsgf** [markbt/streampager#8]
When paging a logfile or other append-only file, it would be nice if it noticed that there was new content and displayed it. At the moment it only shows the original extent of the file.

**Comment by jsgf** [comment]
I guess this is already listed in the TODO section.

**Comment by markbt** [comment]
For memory mapped files, it's quite naive right now.  It just maps the file at the start of the program, and so you get this issue and also #9.

Windows isn't a supported platform, but I think mmapping like this doesn't work too well there, either.

I need to look into what the proper way to use memory mapping for long-term access to files is.  Presumably we also need to watch the file with fsnotify (or equivalent) and trigger reloading of the file if it changes.

**Comment by jsgf** [comment]
Periodic polling is probably fine. 

I'm wondering if mmap has enough benefits to justify using it. What's wrong with pread? mmap is nice because it avoids a kernel->user copy, but that doesn't seem like a big issue here. It's otherwise hard to use correctly or efficiently (SIGBUS truncation issues, per-page fault overhead).
